version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: myapp
    container_name: myapp
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=subasta
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: myapp-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
